feat: text 추가, 오픈, 수정, 이동 기능 구현
zayoonkim/SVGGraphicEditor pull request #12
Opened 2024-11-15 09:35 UTC by zayoonkim

2024-11-15 11:42 UTC, dha-thinkfree requested changes
코드 확인했습니다.
커멘트 확인 부탁드립니다.
자잘한 오탈자는 별도 커멘트 드리지 않았습니다. (나중에 코드 정리할때 확인해주세요)

2024-11-15 11:42 UTC, dha-thinkfree commented on src/controller/Connector.js
> +    static getElementById(id) {
element란 단어는 아무래도 DOM(view)을 의미하는 것 같으니.. object를 쓰는건 어떨까요? (getObjectById)

그러고보니.. 이 파일 이름이 파스칼케이스로 되어있군요.. (Connector.js)

2024-11-15 11:42 UTC, dha-thinkfree commented on src/controller/actionGenerator.js
> +        id: "moveText",
코드 확인해보니 op의 id는 사용하지 않는거죠?
만약 사용하지 않는다면 shapeId, textId를 나누지 않고, nanoid를 통해 만들어낸 값을 해당 프로퍼티로 사용하는게 좋을 것 같습니다.

2024-11-15 11:42 UTC, dha-thinkfree commented on src/controller/core.js
> +        setAddingText() {
canvasView의 함수와 같은 이름을 사용하는것이 좋을 것 같습니다.

2024-11-15 11:42 UTC, dha-thinkfree commented on src/controller/selector.js
> +    const shape = Connector.getElementById(Selector.getSelectedShapeId());
여기도 마찬가지로 shape이 아닌 object를 쓰는게 더 좋을 것 같습니다.
혹은 더 괜찮은 단어가 있다면 그걸로 쓰셔도 좋습니다.

예)
const object = Connector.getObjectById(Selector.getSelectedObjId());
...
if (object.getType() === "text") {
...

2024-11-15 11:42 UTC, dha-thinkfree commented on src/model/text.js
> +    type(newType) {
type도 id와 마찬가지로 변경될 일이 없으므로 getType으로 반환만 해주면 좋을 것 같습니다.
이 부분은 나중에 코드정리 하실때 반영해주셔도 됩니다.

2024-11-15 11:42 UTC, dha-thinkfree commented on src/view/canvasView.js
> +    const textElement = document.createElementNS("http://www.w3.org/2000/svg", "text");
메신저로 말씀하셨던 내용이 이 내용들 맞죠?
일단 이대로 구현해보시고, 추후 레퍼런스 페이지에서 어떤식의 구조로 텍스트 입력을 받는지 확인해보셔도 좋을 것 같습니다.

2024-11-16 04:56 UTC, zayoonkim commented on src/controller/Connector.js
> +    static getElementById(id) {
object가 적합한 것 같습니다!!!!!

네.. 파일명을 다시 바꾸니까 저번처럼 vscode에 에러가 많이 나서 마지막에 고쳐야겠다고 생각중이었습니다 ㅜㅜ

2024-11-16 04:56 UTC, zayoonkim commented on src/controller/actionGenerator.js
> +        id: "moveText",
넵 알겠습니다 !! op/rop 구현하면서 반영해보겠습니다!

2024-11-16 05:43 UTC, dha-thinkfree commented on src/controller/core.js
> +        setAddingText() {
아, 이 함수 이름을 setAddingTextMode가 나을 것 같다는 커멘트였습니다!
다음에 코드 정리할 때 반영해주세요~

2024-11-16 05:44 UTC, dha-thinkfree approved these changes
코드 확인했습니다.
커멘트 확인 후 추후 커밋에 반영 부탁드립니다!

2024-11-16 05:44 UTC, merged