feat: open/save 구현
zayoonkim/SVGGraphicEditor pull request #14
Opened 2024-11-19 06:23 UTC by zayoonkim

2024-11-19 07:25 UTC, dha-thinkfree requested changes
코드 확인했습니다.
커멘트 확인 부탁드립니다.

2024-11-19 07:25 UTC, dha-thinkfree commented on src/controller/Connector.js
> +        if (existingCanvas) {
이 부분은 refresh 때문에 들어간걸까요?

2024-11-19 07:25 UTC, dha-thinkfree commented on src/model/canvas.js
> +      transform: {
이 부분도 도형/텍스트와 같이 통일되면 좋겠네요.
size: { width: this._width, height: this._height }

2024-11-19 07:25 UTC, dha-thinkfree commented on src/view/textView.js
> +        textElement.setAttribute("id", this.text.getId());
여기는 코드가 돌아간 것 같습니다. (캐시가 사라졌네요)

2024-11-19 07:25 UTC, dha-thinkfree commented on src/view/uiView.js
> +    const file = event.target.files[0];
이벤트는 uiView에서 받고 open/save를 전담하는 클래스를 만들어 처리하는것이 좋을 것 같습니다.
(현재 JsonLoader에서 수행하는 내용도 함께 포함되면 좋겠네요.)

2024-11-20 05:39 UTC, zayoonkim commented on src/controller/Connector.js
> +        if (existingCanvas) {
넵 ! 
이 부분을 canvasView로
옮겼는데 한번 확인해주시면 감사하겠습니다..

2024-11-20 05:39 UTC, zayoonkim commented on src/model/canvas.js
> +      transform: {
넵

2024-11-20 06:26 UTC, merged