feat: 캔버스, 도형 undo/redo 구현
zayoonkim/SVGGraphicEditor pull request #15
Opened 2024-11-21 01:15 UTC by zayoonkim

2024-11-21 04:43 UTC, dha-thinkfree requested changes
코드 확인하였습니다. 커멘트 확인 부탁드립니다.
추가적으로 현재 코드를 봤을땐 undo/redo에 따라 UiView 갱신이 되지 않을 것 같은데.. 맞을까요?

2024-11-21 04:43 UTC, dha-thinkfree commented on src/controller/actionGenerator.js
> +        shapeId: shapeId,
도형 삽입, 삭제에 대한 operation을 만들어주는 내부함수가 있으면 좋을 것 같습니다.

예)
function _getInsertingShapeOperation(id, type, pos, size) {
  return {
    ...
  };
}

2024-11-21 04:43 UTC, dha-thinkfree commented on src/view/shapeView.js
> +    const selectedShape = Connector.getObjectById(shapeId);
자기 자신의 모델에 접근하는것이니 this.shape으로 해도 되지 않을까요??
혹시 id를 인자로 추가한 이유가 따로 있을까요?

2024-11-21 04:43 UTC, dha-thinkfree commented on src/view/uiView.js
> +    this.undoButton.addEventListener("click", () => ActionManager.undo());
undo/redo도 사용자 액션이니 ActionGenerator를 호출하는것이 좋을 것 같습니다.

pseudo code)
ActionGenerator.undo() {
  ActionManager.executeAction(ActionManager.getUndoOperation());
}

2024-11-21 04:43 UTC, dha-thinkfree commented on src/controller/actionManager.js
> +    if (this.undoStack.length > 0) {
this.undoStack.length 조건만 있으면 될 것 같습니다.
undo/redo 가능 여부에 따라 UiView의 아이콘의 활성화 상태도 변경되면 좋을 것 같네요!

2024-11-21 04:57 UTC, zayoonkim commented on src/view/shapeView.js
> +    const selectedShape = Connector.getObjectById(shapeId);
아.. 제가 잘못 생각했던 것 같습니다!

2024-11-21 05:12 UTC, dha-thinkfree commented
추가적으로 도형 삽입/삭제 시 선택 상태를 갱신해주는 코드가 있으면 좋을 것 같습니다. (코드상으로는 해당 부분이 안보이는데, 이미 처리를 하고 있다면 이 커멘트는 무시해주세요!)

예) 도형 삽입 시 - 삽입된 도형 선택 상태 (툴바도 도형으로 갱신)
도형 제거 시 - 캔버스 선택 상태 (툴바도 캔버스로 갱신)

2024-11-23 07:47 UTC, dha-thinkfree approved these changes
코드 확인하여 merge 하겠습니다.
커멘트 내용 확인 부탁드립니다!

2024-11-23 07:47 UTC, dha-thinkfree commented on src/controller/actionManager.js
> +import UIView from "../view/uiView.js";
사용하는곳이 없으니 다음 커밋에 제거해주세요~

2024-11-23 07:47 UTC, dha-thinkfree commented on src/controller/actionHandler.js
> +        UIView.setCanvasToolbarState();
이 부분은 uiView의 이벤트 핸들러에서 수행할 수 있을까요?
가능하다면 다음 커밋에 반영 부탁드립니다!

2024-11-23 07:47 UTC, merged