Refactor: core-ui 모듈 추가, selector 추가
zayoonkim/SVGGraphicEditor pull request #5
Opened 2024-11-06 10:32 UTC by zayoonkim

2024-11-06 11:06 UTC, dha-thinkfree requested changes
코드 확인하였습니다.

2024-11-06 11:06 UTC, dha-thinkfree commented on src/model/shape.js
> +        this.fillcolor = newColor;
여기도 canvas와 마찬가지로 모델 값 세팅 함수 만들어서 저장하면 좋겠습니다.

2024-11-06 11:06 UTC, dha-thinkfree commented on src/controller/UIConnector.js
> +export default class UIConnector {
Connector로 변경 부탁드립니다.

2024-11-06 11:06 UTC, dha-thinkfree commented on src/view/uiView.js
> +    this.widthInput.value = UIConnector.getCanvasSize().width;
canvas 사이즈는 한번만 받아와 변수에 저장해두고 사용하는게 좋을 것 같습니다. (33,43 라인 중복호출)

2024-11-06 11:06 UTC, dha-thinkfree commented on src/view/canvasView.js
>          }
} else { 로 붙여서 써주세요

2024-11-06 11:06 UTC, dha-thinkfree commented on src/view/canvasView.js
> +                width: 100,
static한 정보는 constant에 저장해주는게 좋을 것 같습니다.

2024-11-06 11:06 UTC, dha-thinkfree commented on src/view/canvasView.js
> +            UIConnector.addShape({
canvasView도 core이기때문에 굳이 connector를 통하지 않아도 될 것 같아요 (기존처럼 ActionGenerator 바로 호출)

2024-11-06 11:06 UTC, dha-thinkfree commented on src/view/canvasView.js
> +            UIConnector.addShape({
여기도 111번 라인과 같습니다. (기존처럼 ActionGenerator 바로 호출)

2024-11-06 12:35 UTC, dha-thinkfree commented on src/view/uiView.js
> +    ActionGenerator.addShapeModel(shapeType);
메신저로 말씀드린 내용처럼, 모델에 영향을 주는 행위가 아니니 ActionGenerator를 호출하지 말고 Connector를 통해 값 세팅만 하는게 좋을 것 같습니다.

2024-11-07 04:35 UTC, dha-thinkfree reviewed
코드 확인하였습니다.
커멘트 확인 부탁드립니다.

2024-11-07 04:35 UTC, dha-thinkfree commented on src/constant.js
> +    height: 100,
불필요한 콤마로 보입니다. (20라인에는 세미콜론이 빠졌네요)
다음 커밋에 반영해주세요~

2024-11-07 04:35 UTC, dha-thinkfree commented on src/controller/Connector.js
> +    }
함수간 한줄씩 띄어쓰기 부탁드립니다.
다음 커밋에 반영해주세요~

2024-11-07 04:35 UTC, dha-thinkfree commented on src/controller/actionGenerator.js
> +        position : position,
띄어쓰기 들어갔네요. (58 라인도 마찬가지)
다음 커밋에 반영해주세요~

2024-11-07 04:35 UTC, dha-thinkfree commented on src/controller/actionHandler.js
> +        // Connector.getCanvas.updateShapeColor(op.value);
아직 구현 전이긴 하지만, 도형 모델 획득 후 수행하는게 좋을 것 같습니다.
구현하실때 참고 부탁드립니다.

2024-11-07 04:35 UTC, dha-thinkfree commented on src/controller/actionHandler.js
> +        Connector.insertShape(op.shapeType, op.position);
updateCanvasSize처럼 canvas를 받아와서 호출하지 않고 connector를 통해 처리한 이유가 따로 있을까요?

2024-11-07 04:35 UTC, dha-thinkfree commented on src/controller/core.js
> +        this.uiView = new UIView();
uiView는 core 영역이 아닌데 여기에 저장해둔 이유가 따로 있을까요?

2024-11-07 04:35 UTC, dha-thinkfree commented on src/controller/jsonLoader.js
> +            Core.registerJson(parsedJson.canvas)
세미콜론 빠졌네요
다음 커밋에 반영해주세요~

2024-11-07 04:35 UTC, dha-thinkfree commented on src/model/shape.js
> +        this.fillcolor = newColor;
this.fillColor(newFillColor); 로 하는게 좋겠습니다.
다음 커밋에 반영해주세요~

2024-11-07 04:54 UTC, zayoonkim commented on src/controller/actionHandler.js
> +        Connector.insertShape(op.shapeType, op.position);
아,
어제까지는 position을 모델로 바로 줄 수 없고 커넥터로 받아올 수 있었어서 좀 꼬였던 것 같습니다!
이제는 구조가 바뀌어서 다른 것들처럼 바꾸었습니다!!!

2024-11-07 05:07 UTC, zayoonkim commented on src/controller/actionHandler.js
> +        // Connector.getCanvas.updateShapeColor(op.value);
넵!!

2024-11-07 05:16 UTC, zayoonkim commented on src/controller/core.js
> +        this.uiView = new UIView();
_생각지 못했습니다.._

2024-11-07 06:11 UTC, merged